# Uncomment to enable Corne RGB underglow.
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment to enable Corne OLED display.
# CONFIG_ZMK_DISPLAY=y

# Keyboard name.
# CONFIG_ZMK_KEYBOARD_NAME="Corne"

# Sleep after 30 minutes idle.
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Increase BT TX power.
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_KEYBOARD_NAME="Corne"
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
